#+TITLE: Free Software for a good climate
#+AUTHOR: David Arroyo Menéndez
#+OPTIONS: H:2 toc:nil num:t
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation]
#+BEAMER_THEME: Madrid
#+COLUMNS: %45ITEM %10BEAMER_ENV(Env) %10BEAMER_ACT(Act) %4BEAMER_COL(Col) %8BEAMER_OPT(Opt)

* Summary
** BSC machines in a photo

[file:img/davidam-bsc.jpg]

** BSC software in a picture

[file:img/bsc.png]

** BSC Software (I): R2D2 and C3PO

Retrieve Remote Data Directly (*R2D2*) is a tool to download data
using different protocols and sources like http, ftp, opendap, mars
(ECMWF), etc.

Correctness Checker for Climate Predictions and Observations (*C3PO*)
is a tool that modifies the original files downloaded from external
sources (with R2D2) to the common ES format.

** BSC Software (II): StartR and s2dverification

*startR*: Retrieval and processing of multidimensional datasets

*s2dverification* (seasonal to decadal verification) is an R framework
that aids in the analysis of forecasts from the data retrieval stage,
through computation of statistics and skill scores against
observations, to visualisation of data and results

** BSC Software (III): Autosubmit and ecFlow

*Autosubmit*: a versatile tool to manage Weather and Climate Experiments
in diverse Supercomputing Environments.

The performance tools developed at BSC are an open-source project
targeting not only to detect performance problems but to understand
the applications' behavior.

*ecFlow* is a C++ application and features a client-server
model. Installation for server and clients is the same.

ecFlow can submit tasks directly to the relevant queuing system on the
target machine.

ecFlow submits jobs and receives acknowledgements from jobs when they
change status and when they send events. It does this using child
commands embedded in the ecFlow scripts

** ArcGIS

ArcGIS is a platform for organizations to create, manage, share, and
analyze spatial data. It consists of server components, mobile and
desktop applications, and developer tools.

#+BEGIN_SRC bash
$ pip3 install arcgis
#+END_SRC

** Som Energia

Som Energia is a green energy cooperative with a good free software
repository

#+BEGIN_SRC bash
$ firefox https://github.com/Som-Energia &
#+END_SRC

* License
Copyright (C) 2019 David Arroyo Menendez
    Permission is granted to copy, distribute and/or modify this document
    under the terms of the GNU Free Documentation License, Version 1.3
    or any later version published by the Free Software Foundation;
    with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
    A copy of the license is included in [[https://www.gnu.org/copyleft/fdl.html][GNU Free Documentation License]].
