#+TITLE: Storing Data
#+AUTHOR: David Arroyo Menéndez
#+OPTIONS: H:2 toc:nil num:t
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation]
#+BEAMER_THEME: Madrid
#+COLUMNS: %45ITEM %10BEAMER_ENV(Env) %10BEAMER_ACT(Act) %4BEAMER_COL(Col) %8BEAMER_OPT(Opt)


* Summary
** Basics
#+BEGIN_SRC bash
$ python3 for.py # arrays
$ python3 lists.py
$ python3 diccionarios.py
$ python3 conjuntos.py
#+END_SRC

** Ficheros
#+BEGIN_SRC bash
$ python3 write.py
$ python3 list2file.py
$ python3 json-example.py
$ python3 items.py
$ python3 csv-example.py
$ python3 rss-example.py
#+END_SRC

** Pandas
#+BEGIN_SRC bash
$ python pandas-example.py
$ python pandas-10min.py
$ python pandas-creating-dataframe-from-arrays.py
$ python pandas-creating-dataframe.py
$ python3 pandas-plot.py
$ python3 jsonpandas.py
#+END_SRC

** NetCDF
#+BEGIN_SRC bash
$ python3 netcdf-example.py
$ python3 netcdf-example2.py
$ python3 netcdf-example3.py
$ python3 netcdf-example4.py
#+END_SRC

** Pytables
#+BEGIN_SRC bash
$ python3 objecttre.py
#+END_SRC

** Databases
#+BEGIN_SRC bash
$ python3 sqlite.py
$ python3 sqlite2.py
$ python3 mongo-tutorial.py
$ python3 mysql-example.py
#+END_SRC

** HDF5
#+BEGIN_SRC bash
$ python3 h5_cmprss.py
$ python3 h5_crtgrpar.py
$ python3 h5_crtgrpd.py
$ python3 h5_crtgrp.py
$ python3 h5_rdwt.py
#+END_SRC

** Elasticsearch: Introduction

This document is only my personal notes about this software.

Elasticsearch is a highly scalable open-source full-text search and
analytics engine. It allows you to store, search, and analyze big
volumes of data quickly and in near real time. It is generally used as
the underlying engine/technology that powers applications that have
complex search features and requirements.

** Elasticsearch: Installation

https://www.elastic.co/guide/en/elasticsearch/reference/current/_installation.html

** Elasticsearch: Checking
#+BEGIN_SRC bash
http://localhost:9200/
#+END_SRC

** Elasticsearch: List indexes
#+BEGIN_SRC bash
http://localhost:9200/_cat/indices
#+END_SRC

** Elasticsearch: List indexes in json
#+BEGIN_SRC bash
$ curl 'http://localhost:9200/_cat/indices?pretty' -H "Accept: application/json"
#+END_SRC
** Elasticsearch: Delete index
#+BEGIN_SRC bash
$ curl -XDELETE localhost:9200/commits
#+END_SRC
** Elasticsearch: Show an index
#+BEGIN_SRC bash
$ wget http://localhost:9200/dam-index/
#+END_SRC

** Elasticsearch: Searching in an index
#+BEGIN_SRC bash
$ wget -c http://localhost:9200/dam-index/_search
#+END_SRC

** Elasticsearch: The cluster state API allows to get a comprehensive state information of the whole cluster.
#+BEGIN_SRC bash
$ wget http://localhost:9200/_cluster/state
#+END_SRC

** Elasticsearch: Master
#+BEGIN_SRC bash
http://localhost:9200/_cat/master?v
#+END_SRC

** Elasticsearch: Show nodes
#+BEGIN_SRC bash
$ wget -c http://localhost:9200/_cat/nodes?h=ip,port,heapPercent,name
$ curl http://localhost:9200/_cat/nodes?v
#+END_SRC

** Elasticsearch: Show cluster health
#+BEGIN_SRC bash
http://localhost:9200/_cluster/health
#+END_SRC

** Elasticsearch: Elasticdump
*** json to the index
#+BEGIN_SRC bash
$ elasticdump --input=git_openstack_data.json --output=http://localhost:9200 --output-index=dam-index --type=data
$ elasticdump --input=git_openstack_mapping.json --output=http://localhost:9200 --output-index=dam-index --type=mapping
#+END_SRC
*** index data to json
#+BEGIN_SRC bash
$ elasticdump  --input=http://production.es.com:9200/my_index --output=/data/my_index_mapping.json --type=mapping
$ elasticdump  --input=http://production.es.com:9200/my_index --output=/data/my_index.json --type=data
#+END_SRC

** License
Copyright (C) 2019 David Arroyo Menendez
    Permission is granted to copy, distribute and/or modify this document
    under the terms of the GNU Free Documentation License, Version 1.3
    or any later version published by the Free Software Foundation;
    with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
    A copy of the license is included in [[https://www.gnu.org/copyleft/fdl.html][GNU Free Documentation License]].

[[https://www.gnu.org/copyleft/fdl.html][file:https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/GFDL_Logo.svg/200px-GFDL_Logo.svg.png]]
