import wikipedia
print(wikipedia.search("Bill"))
print(wikipedia.suggest("Bill cliton"))
#print(wikipedia.summary("Ubuntu"))
# print(wikipedia.summary("key"))
# print(wikipedia.summary("Key (cryptography)"))
print(wikipedia.page("Ubuntu"))
print(wikipedia.page("Python").content)
print(wikipedia.page("Python").url)
print(wikipedia.page("Python").references)
print(wikipedia.page("Python").title)
print(wikipedia.page("Python").categories)
print(wikipedia.page("Ubuntu").links)
print(wikipedia.geosearch(37.787, -122.4))
print(wikipedia.page(37.787, -122.4))
wikipedia.set_lang("de")
print(wikipedia.summary("ubuntu", sentences=2))

print(wikipedia.languages())
print(wikipedia.page("ubuntu").images[0])
print(wikipedia.page("Ubuntu").html())
